'use strict';
const $=s=>document.querySelector(s);
const icons={chart:'M4 19V9m5 10V4m5 15v-7m5 7V7M2 22h21',project:'M4 4h16v16H4zM8 8v8m4-8v4m4-4v6',branch:'M6 4v12a3 3 0 003 3h8M6 12h8a3 3 0 003-3V5M4 3h4v4H4zm11 0h4v4h-4zm0 14h4v4h-4z',grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z',book:'M5 3h14a2 2 0 012 2v16H6a3 3 0 010-6h15M6 3v12m6-12v7l2-2 2 2V3',search:'M10 3a7 7 0 100 14 7 7 0 000-14zm5 12 6 6',arrow:'M4 12h15m-6-6 6 6-6 6',left:'M20 12H5m6-6-6 6 6 6',bell:'M5 17h14l-2-3V9a5 5 0 00-10 0v5zM10 21h4',play:'m8 4 12 8-12 8z',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z',settings:'M12 8a4 4 0 100 8 4 4 0 000-8zM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',info:'M12 2a10 10 0 100 20 10 10 0 000-20zm0 8v7m0-11v1',close:'m6 6 12 12M6 18 18 6',plus:'M12 4v16M4 12h16',edit:'m5 15 11-11 4 4L9 19l-5 1zM14 6l4 4',folder:'M3 7V5h7l2 3h9v12H3z',file:'M5 3h9l5 5v13H5zm9 0v6h5M8 13h8m-8 4h6',risk:'m12 3 10 18H2zm0 6v5m0 3v1',lock:'M5 10h14v11H5zM8 10V6a4 4 0 018 0v4m-4 4v3',check:'m5 12 4 4L19 6',list:'M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.file}"/></svg>`;
function hydrate(){document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toFixed(2),tag=(s,t='')=>`<span class="tag ${t}">${s}</span>`;
const projects=[{code:'M27-Q',name:'27″ QHD 办公显示器',stage:'PDCP',bom:610,goal:630,risk:'待收敛',spec:'2560 × 1440 / 165 Hz / IPS'}, {code:'G32-U',name:'32″ UHD 创作显示器',stage:'CDCP',bom:1168,goal:1250,risk:'已达标',spec:'3840 × 2160 / 144 Hz / IPS'}, {code:'M24-F',name:'24″ FHD 入门显示器',stage:'ADCP',bom:385,goal:410,risk:'已达标',spec:'1920 × 1080 / 100 Hz / IPS'}, {code:'D27-C',name:'27″ USB-C 商用显示器',stage:'PDCP',bom:784,goal:null,risk:'目标待确认',spec:'2560 × 1440 / 100 Hz / IPS'}];
const domains=[['显示模组',420,400,'替代验证'],['驱动方案',95,110,'配套依赖'],['结构组件',48,48,'冻结明细'],['电源方案',27,27,'冻结明细'],['包装',12,12,'冻结明细'],['ODM 加工',8,8,'冻结明细']];
const books=[{code:'M27-Q',name:'方案收敛',sub:'27″ QHD 显示器',tone:'blue',period:'2026.08 — 09'},{code:'G32-U',name:'规格探索',sub:'32″ UHD 创作显示器',tone:'white',period:'2026.09'},{code:'MEMO',name:'工作备忘',sub:'判断 · 方法 · 随手记',tone:'slate',period:'2026.09'}];
let notes=[
{id:1,book:0,date:'2026.09.06',type:'决策记录',title:'把屏的节省，和驱动的增本一起看',content:'显示模组替代可以节省 20.00 元，但需要增加 15.00 元的驱动补偿。单看某个器件会放大收益，整包才是可交付的方案。\n\n当前标准成本为 640.50 元。按 5% 平台费率计算，变更包实施后预计为 635.25 元，距离 630.00 元财务目标仍有 5.25 元缺口。',next:'完成样机显示效果与驱动验证。证据补齐前，不标记实施。',source:'change'},
{id:2,book:0,date:'2026.09.05',type:'待跟进',title:'先对齐包装范围，再比较第三家报价',content:'ODM C 的报价未明确包装与附件范围。本轮暂不把它列入可比低价。\n\n保留原报价，补充数量、税费、交付及规格条件后再复核，不通过手动改价消除差异。',next:'请供应商补齐包装、附件和交付条件。',source:'quote'},
{id:3,book:0,date:'2026.09.04',type:'工作进展',title:'评审之前，把事实版本固定下来',content:'成本评审固定 BOM v3、产品规格 v3 与 5% 平台费率。\n\n会议中分别讨论当前事实、财务目标和未实施机会，避免不同时间点的数字混在一起。',next:'下一次阶段成本包输出前，重新核对来源。',source:'version'},
{id:4,book:1,date:'2026.09.05',type:'心得',title:'刷新率的取舍，回到真实使用场景',content:'目前讨论集中在刷新率提升，但已有反馈还不能证明用户愿意为此付出更多。\n\n将原声主题关联到显示效果与使用场景，区分明确需求与推断。',next:'补充用户场景与竞品规格证据。'},
{id:5,book:1,date:'2026.09.03',type:'工作进展',title:'两条屏方案，分别保留比较依据',content:'方案 A 的成本更低，方案 B 的显示能力更强。两条路线解决的问题不同。\n\n先记录性能边界、报价来源和测试条件，再决定取舍。',next:'分别补齐两条路线的验证记录。'},
{id:6,book:2,date:'2026.09.04',type:'心得',title:'报价低，不等于可比成本低',content:'报价比较前先问三个问题：规格相同吗？费用范围一致吗？交付条件一致吗？\n\n未知项应明确保留，避免把信息缺失误读成成本优势。',next:'把核对条件带入下一次报价评审。'}];
let currentPage='dashboard',currentProject='M27-Q',projectTab='overview',journalMode='albums',selectedBook=0,selectedNote=1,libraryFilter='全部资料',signalFilter='all',editing=null;
let inputIsKeyboard=false;
document.addEventListener('keydown',()=>inputIsKeyboard=true);document.addEventListener('pointerdown',()=>inputIsKeyboard=false);
const quiet=()=>inputIsKeyboard||document.body.classList.contains('motion-off')||matchMedia('(prefers-reduced-motion: reduce)').matches;
function heading(title,desc,action='',symbol=''){return `<div class="page-heading"><div><div class="heading-title">${symbol?icon(symbol):''}<h1>${title}</h1></div><p>${desc}</p></div><div class="heading-actions">${action}</div></div>`;}
function tableProjects(){return `<div class="table-wrap"><table><thead><tr><th>项目</th><th class="num">当前 BOM</th><th>阶段</th><th>目标状态</th></tr></thead><tbody>${projects.map(p=>`<tr><td><button data-project="${p.code}">${p.code}</button><small>${p.name}</small></td><td class="num">¥${money(p.bom)}</td><td>${tag(p.stage)}</td><td>${tag(p.risk,p.risk==='已达标'?'green':p.goal?'amber':'gray')}</td></tr>`).join('')}</tbody></table></div>`;}
function dashboard(){return heading('今日工作台','今天优先处理影响降本的成本事项，让判断有据可循。','<span class="eyebrow">2026 / 09 / 06</span>','chart')+`<div class="dash-layout"><section class="focus-card"><span class="eyebrow">当前关注 / PDCP</span><h2>M27-Q</h2><p>27″ QHD 显示器 · 方案收敛</p><div class="glass-orbit" aria-label="目标差额10.50元，圆环为装饰"><div class="orbit-core"><small>待消除差额 / 元</small><strong>10<span>.50</span></strong></div></div><div class="focus-detail"><span>当前标准成本</span><b>¥640.50</b></div><div class="focus-detail"><span>财务目标</span><b>¥630.00</b></div><p class="focus-bottom">下一步先复核屏方案与驱动补偿。<br>当前版本：冻结 BOM v3</p><button class="button" data-project="M27-Q">继续项目${icon('arrow')}</button></section><div class="metrics">${[['project','进行中项目','4','个','4 个项目合计'],['risk','目标风险','1','项','另 1 个目标待确认'],['file','待审报价','1','项','包装范围待补齐'],['chart','已确认方案净节省','5.25','元/台','含平台费 · 尚未实施']].map(([i,l,v,u,d])=>`<section class="metric glass"><div class="metric-label"><span class="metric-icon">${icon(i)}</span>${l}</div><strong>${v}<small>${u}</small></strong><small>${d}</small></section>`).join('')}</div><section class="panel glass dash-projects"><div class="panel-head"><h2>项目成本进展</h2><button class="text-button" data-page="projects">全部项目${icon('arrow')}</button></div>${tableProjects()}</section><section class="panel glass task-panel"><div class="panel-head"><h2>今日优先处理</h2><span>3 项</span></div>${[['change','复核 M27-Q 的整包成本影响','节省与必要增本一起确认'],['quote','补齐第三家 ODM 报价条件','包装、附件与交付范围'],['target','确认 D27-C 的财务目标','目标未设定，不判为达标']].map(([d,t,s],i)=>`<button class="task-row" data-dialog="${d}"><span>${i+1}</span><span><b>${t}</b><small>${s}</small></span></button>`).join('')}<div class="task-note"><strong>机会成立，还需要实施证据</strong><p>净节省 ¥5.25 / 台，当前事实成本保持不变。</p></div></section><section class="panel glass cost-distribution"><div class="panel-head"><div><h2>项目成本分布</h2><p>当前 4 个项目 · 单台 BOM 成本，人民币</p></div><button class="text-button" data-page="projects">查看明细${icon('arrow')}</button></div><div class="chart-bars" role="img" aria-label="G32-U 1168元，D27-C 784元，M27-Q 610元，M24-F 385元">${[1168,784,610,385].map(n=>`<div class="chart-bar" style="--h:${n/12}px"><b>¥${money(n)}</b></div>`).join('')}</div><div class="chart-labels"><span>G32-U</span><span>D27-C</span><span>M27-Q</span><span>M24-F</span></div></section><section class="panel glass dash-signals"><div class="panel-head"><h2>报价决策抓手</h2><button class="text-button" data-page="intelligence">全部${icon('arrow')}</button></div><div class="quote-signal"><strong>27″ 显示模组 · 替代方案</strong><p>关联 CP–014，需连同驱动补偿评估。</p><b>−¥5.00</b> <small class="muted">BOM 净变化 / 台</small><br><button class="text-button" data-dialog="change">查看依赖与证据${icon('arrow')}</button></div></section></div>`;}
function projectContent(){const p=projects.find(p=>p.code===currentProject);if(projectTab==='quote')return `<section class="panel glass"><div class="panel-head"><div><h2>供应商整机报价</h2><p>CNY · 未税 · 1 台 · EXW · 产品规格 v3</p></div>${tag('同口径核对')}</div>${p.code==='M27-Q'?`<div class="table-wrap"><table><thead><tr><th>供应商</th><th class="num">整机报价</th><th>可比状态</th><th>来源</th></tr></thead><tbody><tr><td>ODM A</td><td class="num">¥672.00</td><td>${tag('条件已齐','green')}</td><td><button class="text-button" data-dialog="quote">原始报价</button></td></tr><tr><td>ODM B</td><td class="num">¥658.00</td><td>${tag('条件已齐','green')}</td><td><button class="text-button" data-dialog="quote">原始报价</button></td></tr><tr><td>ODM C</td><td class="num">待补齐</td><td>${tag('包装范围待确认','amber')}</td><td><button class="text-button" data-dialog="quote">查看缺项</button></td></tr></tbody></table></div>`:'<div class="empty">此项目的报价明细未在预览中展开。</div>'}</section>`;
if(projectTab==='history')return `<section class="panel glass"><div class="panel-head"><h2>版本档案</h2>${tag('只读事实')}</div>${p.code==='M27-Q'?`<div class="timeline-row"><span class="eyebrow">2026.09.05 / 14:32</span><h3>冻结 BOM v3</h3><p>产品规格 v3 · 平台费率 5% · 标准成本 ¥640.50</p><button class="text-button" data-dialog="version">打开来源快照${icon('arrow')}</button></div><div class="timeline-row"><span class="eyebrow">下一阶段</span><h3>等待新实施证据</h3><p>确认方案不会自动覆盖冻结成本。</p></div>`:'<div class="empty">本预览未展开该项目的版本档案。</div>'}</section>`;
return `<section class="panel glass project-cost"><div><div class="cost-caption">当前标准成本 · CNY / 台</div><div class="big-cost"><small>¥</small>${money(p.bom*1.05)}</div><div class="cost-caption">BOM ${money(p.bom)} + 平台费 ${money(p.bom*.05)} · 5%</div></div><div class="cost-compare"><div><span class="muted">财务目标</span><b>${p.goal?'¥'+money(p.goal):'待确认'}</b></div><div><span class="muted">与目标差额</span><b class="${p.goal&&p.bom*1.05>p.goal?'bad':'good'}">${p.goal?(p.bom*1.05>p.goal?'+':'−')+'¥'+money(Math.abs(p.bom*1.05-p.goal)):'—'}</b></div></div><div class="monitor-3d" aria-hidden="true"><div class="monitor-screen"><span>${p.code}</span></div><div class="monitor-stand"></div><div class="monitor-foot"></div></div></section>${p.code==='M27-Q'?`<div class="split"><section class="panel glass"><div class="panel-head"><div><h2>${projectTab==='measures'?'方案目标与净影响':'成本落在哪里'}</h2><p>未计平台费 · ¥ / 台 · 方案尚未实施</p></div></div><div class="table-wrap"><table><thead><tr><th>成本领域</th><th class="num">当前 BOM</th><th class="num">方案目标</th><th class="num">变化</th><th>依据</th></tr></thead><tbody>${domains.map(([n,c,t,s])=>`<tr><td>${n}</td><td class="num">${money(c)}</td><td class="num">${money(t)}</td><td class="num ${t<c?'good':''}">${t===c?'—':(t>c?'+':'−')+money(Math.abs(t-c))}</td><td><button class="text-button" data-dialog="${t===c?'version':'change'}">${s}</button></td></tr>`).join('')}<tr><td><b>合计</b></td><td class="num"><b>610.00</b></td><td class="num"><b>605.00</b></td><td class="num good"><b>−5.00</b></td><td></td></tr></tbody></table></div></section><aside class="panel glass decision">${tag('技术可行 · 尚未实施')}<h3>屏方案替代<br>及驱动补偿</h3><p>CP–014 · 必要依赖一起确认，金额一起守恒。</p><div class="delta-row"><span>显示模组替代</span><b class="good">−¥20.00</b></div><div class="delta-row"><span>驱动能力补偿</span><b>+¥15.00</b></div><div class="delta-row"><span>预计标准成本</span><b>¥635.25</b></div><p style="margin-top:13px">仍有 ¥5.25 缺口待覆盖。</p><button class="button" data-dialog="change">查看整包证据${icon('arrow')}</button></aside></div>`:`<section class="panel glass"><h2>成本来源</h2><p class="muted" style="margin-top:12px">已展示该项目的汇总示例。领域明细在正式接入时读取该项目自身来源，预览不复用 M27-Q 的明细。</p></section>`}`;}
function projectPage(){const p=projects.find(p=>p.code===currentProject);return heading('项目','让规格、报价与决策，落在同一个项目里。',`<button class="button" data-dialog="package">${icon('file')}阶段成本包</button>`,'project')+`<div class="project-shell"><aside class="panel glass project-index"><h2>项目档案 · 4</h2>${projects.map(x=>`<button class="project-item ${x.code===p.code?'active':''}" data-project="${x.code}" aria-pressed="${x.code===p.code}"><strong>${x.code}</strong><small>${x.name}</small><small>${x.stage} · ${x.risk}</small></button>`).join('')}</aside><div><div class="panel-head"><div><h2 style="font-size:22px">${p.code} <span style="font-size:13px;font-weight:400;color:#7585a1">${p.name}</span></h2><p>${p.spec}</p></div>${tag(p.stage)}</div><div class="tabs" role="tablist" aria-label="项目工作区">${[['overview','项目总览'],['quote','BOM 与报价'],['measures','目标与措施'],['history','版本档案']].map(([k,n])=>`<button role="tab" aria-selected="${projectTab===k}" class="${projectTab===k?'active':''}" data-project-tab="${k}">${n}</button>`).join('')}<span class="right-meta">产品规格 v3</span></div><div id="project-content">${projectContent()}</div></div></div>`;}
const signals=[{title:'显示模组替代需要驱动补偿',project:'M27-Q',state:'待复核',desc:'一项节省、一项必要增本，整包 BOM 净节省 ¥5.00。',kind:'change'},{title:'第三家整机报价的包装范围缺失',project:'M27-Q',state:'待补证据',desc:'条件不完整，暂不进入可比低价排名。',kind:'quote'},{title:'高刷新率需求缺少场景证据',project:'G32-U',state:'待补证据',desc:'区分原声事实与产品推断，再决定规格调整。',kind:'voice'}];
function intelligence(){return heading('情报','从来源到判断，每一条建议都能追溯。',`<span class="tag gray">演示数据 · 未启动扫描</span>`,'branch')+`<div class="intelligence-top">${[['branch','当前信号','3','覆盖 2 个项目'],['risk','证据待补','2','先补齐条件，再形成结论'],['check','待复核方案','1','确认机会与实施分别记录']].map(([i,t,n,d])=>`<section class="signal-card panel glass"><div class="metric-label"><span class="metric-icon">${icon(i)}</span>${t}</div><strong>${n}</strong><small class="muted" style="margin-left:13px">${d}</small></section>`).join('')}</div><div class="split"><section class="panel glass"><div class="panel-head"><h2>待处理信号</h2><div class="segmented">${[['all','全部'],['evidence','待补证据']].map(([k,v])=>`<button class="${signalFilter===k?'active':''}" data-signal="${k}" aria-pressed="${signalFilter===k}">${v}</button>`).join('')}</div></div>${signals.filter(s=>signalFilter==='all'||s.state==='待补证据').map(s=>`<button class="result signal-result" data-dialog="${s.kind}" style="display:block;width:100%;text-align:left;padding:21px 0;border-bottom:1px solid var(--line)"><div class="panel-head" style="margin-bottom:7px"><strong>${s.title}</strong>${tag(s.state,s.state==='待补证据'?'amber':'')}</div><p class="muted" style="font-size:12px">${s.desc}</p><small style="display:block;margin-top:10px;color:#8a9bb2">${s.project} · 09.06 · 查看来源 →</small></button>`).join('')}</section><aside class="panel glass decision"><span class="eyebrow">判断的边界</span><h3>可解释，<br>才值得进入决策。</h3><p>报价、规格和来源版本共同决定可比性。AI 建议保留为草稿，证据确认后再进入业务流程。</p><div class="evidence-preview"><h3 style="font-size:13px;margin:0">当前工作上下文</h3><p>M27-Q · 产品规格 v3<br>冻结 BOM v3<br>变更包 CP–014</p></div><button class="button" data-dialog="ai">围绕当前项目分析${icon('arrow')}</button></aside></div>`;}
const files=[['产品规格','M27-Q 产品规格 v3','M27-Q','已确认','09.05','version'],['报价文件','第 3 轮 ODM 报价','M27-Q','待补条件','09.05','quote'],['成本快照','BOM v3 冻结快照','M27-Q','已冻结','09.05','version'],['评审记录','屏方案与驱动补偿复核','M27-Q','待实施','09.06','change'],['评审记录','刷新率与使用场景记录','G32-U','待补证据','09.05','voice']];
function fileRows(q=''){return files.filter(f=>(libraryFilter==='全部资料'||f[0]===libraryFilter)&&f.join(' ').toLowerCase().includes(q.toLowerCase())).map(f=>`<tr><td><button data-dialog="${f[5]}">${f[1]}</button><small>${f[0]}</small></td><td>${f[2]}</td><td>${tag(f[3],f[3].startsWith('待')?'amber':'gray')}</td><td>${f[4]}</td><td><button class="text-button" data-dialog="${f[5]}">查看${icon('arrow')}</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">没有匹配资料</td></tr>';}
function library(){return heading('资料库','规格、报价、快照与评审材料，有序归档。',`<button class="button" data-dialog="import">${icon('plus')}导入资料</button>`,'grid')+`<div class="folder-row">${['全部资料','产品规格','报价文件','评审记录'].map(n=>`<button class="folder-card ${libraryFilter===n?'selected':''}" data-folder="${n}" aria-pressed="${libraryFilter===n}"><span class="folder-back"></span><span class="folder-paper"></span><span class="folder-front"><strong>${n}</strong><small>${n==='全部资料'?5:files.filter(f=>f[0]===n).length} 份资料 · 项目来源</small></span></button>`).join('')}</div><section class="panel glass"><div class="filters"><input id="file-search" placeholder="搜索名称、项目、类型" aria-label="搜索资料"><span class="muted" style="font-size:11px">${libraryFilter} · 来源保持关联</span></div><div class="table-wrap"><table><thead><tr><th>资料名称</th><th>关联项目</th><th>状态</th><th>更新日期</th><th></th></tr></thead><tbody id="file-rows">${fileRows()}</tbody></table></div></section>`;}
function albumMarkup(b,i){const count=notes.filter(n=>n.book===i).length;return `<button class="album ${b.tone}" data-book="${i}" aria-pressed="${i===selectedBook}" aria-label="选择 ${b.code} ${b.name} 手账"><span class="album-pages"></span><span class="album-tab"></span><span class="album-cover"><span class="album-eyebrow">COSTHUB / 工作手账</span><span class="album-code">${b.code}</span><span class="album-title">${b.name}</span><span class="album-line"></span><span class="album-bottom"><span>${b.period}</span><span>${String(count).padStart(2,'0')} 篇</span></span></span></button>`;}
function selectedMarkup(){const b=books[selectedBook],rows=notes.filter(n=>n.book===selectedBook);return `<section class="panel glass journal-current"><div class="selected-title"><div><h2>${b.code} · ${b.name}</h2><p>${b.sub} · ${rows.length} 条记录</p></div><button class="button primary" data-open-book="${selectedBook}">${icon('book')}展开手账${icon('arrow')}</button></div>${rows.slice(0,2).map(n=>`<button class="entry-preview" data-note="${n.id}"><span class="date-block">${n.date.slice(-2)}<small>SEP 2026</small></span><span><strong>${esc(n.title)}</strong><p>${n.type} · ${n.source?'有关联证据':'暂无关联证据'}</p></span>${icon('arrow')}</button>`).join('')}</section><aside class="sticky"><h3>下一步，记在这里。</h3><label><input type="checkbox" id="sticky-done" ${notes.find(n=>n.id===2)?.done?'checked':''}>补齐第三家 ODM 的包装范围</label><p>不急着选最低价，<br>先把比较条件放在同一张纸上。</p><small>M27-Q · 待跟进</small></aside>`;}
function journalRows(q=''){const rows=notes.filter(n=>(n.title+' '+n.content+' '+books[n.book].code).toLowerCase().includes(q.toLowerCase()));if(!rows.length)return '<div class="empty">没有匹配记录，试试项目代号或关键词。</div>';if(journalMode==='board')return `<div class="note-board">${rows.map((n,i)=>`<button class="sticky" data-note="${n.id}" style="--angle:${i%2?-1:1}deg"><small>${books[n.book].code} / ${n.type}</small><h3>${esc(n.title)}</h3><p>${esc(n.content.split('\n')[0]).slice(0,90)}</p><small style="margin-top:18px">${n.date} · 打开记录 →</small></button>`).join('')}</div>`;return `<div class="journal-list panel glass">${rows.map(n=>`<div class="list-record"><button data-note="${n.id}"><strong>${esc(n.title)}</strong><p>${books[n.book].code} · ${n.type} · ${n.source?'已关联证据':'暂无证据'}</p></button><time>${n.date}</time></div>`).join('')}</div>`;}
function journal(){return `<div class="page-heading journal-heading"><div><span class="eyebrow">THE WORK JOURNAL / 2026</span><h1>工作手账</h1><p>把日常的判断，收进值得翻阅的记录。</p></div><button class="button primary" id="new-note">${icon('plus')}写一条手账</button></div><div class="journal-tools"><div class="segmented" aria-label="手账视图">${[['albums','手账册'],['board','便签'],['list','记录列表']].map(([k,v])=>`<button data-journal-mode="${k}" class="${journalMode===k?'active':''}" aria-pressed="${journalMode===k}">${v}</button>`).join('')}</div>${journalMode==='albums'?'<span>选择一本，接着上次的思路。</span>':'<input id="journal-search" aria-label="搜索手账记录" placeholder="搜索标题、内容或项目">'}</div>${journalMode==='albums'?`<section class="journal-shelf" aria-label="手账册架"><div class="shelf-floor"></div><div class="album-stage">${books.map(albumMarkup).join('')}</div><div class="shelf-arrows"><button class="icon-button" id="prev-book" aria-label="上一本手账">${icon('left')}</button><button class="icon-button" id="next-book" aria-label="下一本手账">${icon('arrow')}</button></div><div class="shelf-caption" id="shelf-caption"></div></section><div class="journal-below" id="journal-below">${selectedMarkup()}</div>`:'<div id="journal-results">'+journalRows()+'</div>'}`;}
function positionBooks(){if(currentPage!=='journal'||journalMode!=='albums')return;document.querySelectorAll('.album').forEach((e,i)=>{let d=i-selectedBook;if(d>1)d-=books.length;if(d< -1)d+=books.length;const narrow=innerWidth<650,step=narrow?157:innerWidth<1220?235:270;e.style.transition=quiet()?'none':'';e.style.setProperty('--placement',`translateX(${d*step}px) translateY(${d?8:0}px) translateZ(${d?-55:25}px) rotateY(${d?(d>0?-20:20):-7}deg) scale(${d?.87:1})`);e.style.setProperty('--depth',String(5-Math.abs(d)));e.style.opacity='1';e.setAttribute('aria-pressed',String(d===0));});$('#prev-book').disabled=false;$('#next-book').disabled=false;$('#shelf-caption').textContent=`${String(selectedBook+1).padStart(2,'0')} / 03 · ${books[selectedBook].name}`;}
function selectBook(i){selectedBook=(i+books.length)%books.length;positionBooks();$('#journal-below').innerHTML=selectedMarkup();}
function render(){const renders={dashboard,projects:projectPage,intelligence,library,journal};$('#main').innerHTML=`<div class="page-content">${renders[currentPage]()}</div>`;if(quiet())$('#main').firstElementChild.style.animation='none';document.querySelectorAll('.nav').forEach(b=>{b.classList.toggle('active',b.dataset.page===currentPage);b.setAttribute('aria-current',b.dataset.page===currentPage?'page':'false');b.setAttribute('aria-label',b.textContent.trim());});hydrate();positionBooks();}
function page(p){if(!['dashboard','projects','intelligence','library','journal'].includes(p))return;currentPage=p;render();window.scrollTo({top:0});history.replaceState(null,'','#'+p);}
function entryMarkup(n){return `<div class="entry-date"><span>${books[n.book].code} / ${n.type}</span><span>${n.date}</span></div><span class="entry-type">${n.type}</span><h2>${esc(n.title)}</h2><div class="entry-body">${esc(n.content)}</div><div class="entry-next">下一步<br>${esc(n.next||'暂未填写下一步。')}</div><div class="entry-source">${n.source?'关联依据 <button data-dialog="'+n.source+'">'+({change:'CP–014 变更包',version:'冻结 BOM v3',quote:'第 3 轮报价'}[n.source]||'来源')+'</button>':'暂无关联证据'}</div>`;}
function showEntry(id,direction=0){const n=notes.find(n=>n.id===id);if(!n)return;selectedNote=id;selectedBook=n.book;const rows=notes.filter(x=>x.book===selectedBook),index=rows.findIndex(x=>x.id===id);$('#reader-name').textContent=books[selectedBook].code+' · '+books[selectedBook].name;$('#book-code').textContent=books[selectedBook].code;$('#book-subtitle').textContent=books[selectedBook].sub;$('#contents').innerHTML=rows.map((x,i)=>`<button class="toc ${id===x.id?'active':''}" data-toc="${x.id}" aria-current="${id===x.id?'page':'false'}"><span>${String(i+1).padStart(2,'0')}</span>${esc(x.title)}</button>`).join('');$('#entry').innerHTML=entryMarkup(n);$('#page-count').textContent=`${String(index+1).padStart(2,'0')} / ${String(rows.length).padStart(2,'0')} 页`;$('#prev-entry').disabled=index===0;$('#next-entry').disabled=index===rows.length-1;$('#right-leaf').getAnimations().forEach(a=>a.cancel());if(direction&&!quiet())$('#right-leaf').animate([{transform:`rotateY(${direction>0?-9:9}deg)`,opacity:.35},{transform:'rotateY(0)',opacity:1}],{duration:240,easing:'cubic-bezier(.22,1,.36,1)'});}
function openBook(i,id){selectedBook=i;const rows=notes.filter(n=>n.book===i);showEntry(id||rows[0].id);$('#reader').classList.toggle('opening',!quiet());$('#reader').showModal();}
async function closeReader(){const r=$('#reader');if(!r.open)return;const sheet=$('.open-book');sheet.getAnimations().forEach(a=>a.cancel());if(!quiet()){try{await sheet.animate([{opacity:1,transform:'none'},{opacity:0,transform:'translateY(8px) scale(.99)'}],{duration:160,easing:'ease-out'}).finished;}catch{}}if(r.open)r.close();}
$('#reader').addEventListener('cancel',e=>{e.preventDefault();closeReader();});
function turn(d){const rows=notes.filter(n=>n.book===selectedBook),i=rows.findIndex(n=>n.id===selectedNote);if(rows[i+d])showEntry(rows[i+d].id,d);}
function editNote(n){editing=n?.id||null;$('#editor-title').textContent=n?'编辑工作记录':'写一条手账';$('#note-title').value=n?.title||'';$('#note-content').value=n?.content||'';$('#note-next').value=n?.next||'';$('#note-book').value=n?.book??selectedBook;$('#note-type').value=n?.type||'决策记录';$('#editor').showModal();$('#note-title').focus();}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2600);}
function line(k,v){return `<div class="delta-row"><span>${k}</span><b>${v}</b></div>`;}
function dialog(kind){let title='',body='';switch(kind){case 'change':title='CP–014 · 整包复核';body=tag('技术可行 · 尚未实施','amber')+'<h3>必要依赖一起核对</h3>'+line('显示模组替代','−¥20.00')+line('驱动能力补偿','+¥15.00')+line('BOM 净变化','−¥5.00')+line('标准成本净变化 · 含 5% 费率','−¥5.25')+'<div class="evidence-preview"><h3 style="margin:0">仍需完成技术验证</h3><p>补齐样机显示效果与驱动验证。确认机会不等于实施，不覆盖当前冻结成本。</p></div>';break;case 'version':title='冻结 BOM v3';body=tag('M27-Q · 只读快照')+line('冻结时间','2026.09.05 14:32')+line('产品规格','v3 · QHD / 165 Hz')+line('BOM 成本','¥610.00')+line('平台费率','5.00%')+line('标准成本','¥640.50')+'<p>快照绑定规格、明细与费率，不随实时器件价格变化。</p>';break;case 'quote':title='整机报价 · 可比条件';body=line('关联项目','M27-Q')+line('批次','第 3 轮')+line('币种 / 税费','CNY / 未税')+line('数量 / 交付','1 台 / EXW')+line('规格版本','v3')+'<h3>ODM C 尚需补充</h3><p>包装材料与附件范围。条件补齐前不参与可比低价排名。</p>';break;case 'voice':title='刷新率与使用场景';body=tag('G32-U · 待补证据','amber')+'<p>当前记录保留了产品判断，尚未补齐用户场景证据。</p><h3>下一步</h3><p>将原声与产品规格逐项关联，明确哪些是观察，哪些是推断。</p><button class="button" data-jump-note="4">打开关联手账</button>';break;case 'target':title='D27-C · 财务目标待确认';body='<p>缺少财务目标时，显示“待确认”。当前标准成本为 ¥823.20。</p><p>目标确认后才能计算目标差额。预览不会写入正式目标。</p>';break;case 'ai':title='围绕当前工作分析';body=tag('本地 AI · 演示状态')+'<p>此预览没有连接模型。下面演示带来源的协作入口。</p><h3>项目上下文</h3>'+line('项目','M27-Q')+line('规格 / 成本版本','v3 / BOM v3')+'<button class="result" data-dialog="change">解释整包净成本影响<small>使用变更包明细和平台费率</small></button><button class="result" data-dialog="quote">检查报价是否可比<small>核对规格、税费、数量和交付</small></button>';break;case 'package':title='阶段成本包';body='<p>正式产品中复核来源后再生成交付包；预览仅展示来源清单。</p>'+line('当前项目',currentProject)+line('资料范围','规格、BOM、目标、变更包')+'<p>冻结材料与草稿材料分开标注，未知项不补成 0。</p>';break;case 'import':title='导入资料';body='<p>正式接入时复用已有文件导入、解析与确认流程。</p><div class="evidence-preview"><h3 style="margin:0">先归档，再关联业务对象</h3><p>保留原文件、版本和项目关系。此设计预览不上传或读取本地文件。</p></div>';break;case 'activity':title='最近动态';body=line('09.06','复核 CP–014 的整包影响')+line('09.05 14:32','冻结 BOM v3')+line('09.05','记录包装口径缺项')+'<p>以上均为示例事件。正式接入显示真实时间，无记录时保留空状态。</p>';break;case 'settings':title='外观与动效';body='<p>当前设计延续流光玻璃主题。这里的设置仅影响预览。</p><label class="setting-row"><span>界面动效</span><input id="motion-toggle" type="checkbox" '+(!document.body.classList.contains('motion-off')?'checked':'')+'></label><p>系统设置了减少动态时，同样会自动省去空间位移和翻转。</p>';break;case 'search':title='搜索工作空间';body='<input id="global-query" placeholder="项目、记录或资料" aria-label="搜索工作空间内容"><div id="global-results"></div>';break;default:title='流光玻璃 · 设计预览';body='<p>工作台、项目、情报、资料库与工作手账使用统一的蓝白玻璃语言。</p><p>手账支持选册、展开、目录、翻页、便签、列表与编辑。全部数据为虚构；新记录只保存在当前页面内存，刷新后恢复。</p><p>正式业务代码、数据库与模型连接均未更改。</p>';}
$('#drawer-title').textContent=title;$('#drawer-body').innerHTML=body;if(!$('#drawer').open)$('#drawer').showModal();if(quiet())$('#drawer').style.animation='none';else $('#drawer').style.animation='';if(kind==='search'){searchResults('');$('#global-query').focus();}}
function searchResults(q){const query=q.toLowerCase();$('#global-results').innerHTML=projects.filter(p=>(p.code+p.name).toLowerCase().includes(query)).map(p=>`<button class="result" data-search-project="${p.code}">${p.code}<small>${p.name} · 项目</small></button>`).join('')+notes.filter(n=>(n.title+books[n.book].code).toLowerCase().includes(query)).map(n=>`<button class="result" data-jump-note="${n.id}">${esc(n.title)}<small>${books[n.book].code} · 手账</small></button>`).join('');if(!$('#global-results').innerHTML)$('#global-results').innerHTML='<p>没有匹配结果。</p>';}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
if(b.dataset.page)page(b.dataset.page);
if(b.classList.contains('brand')){e.preventDefault();page('dashboard');}
if(b.dataset.project){currentProject=b.dataset.project;projectTab='overview';page('projects');}
if(b.dataset.projectTab){projectTab=b.dataset.projectTab;render();document.querySelector(`[data-project-tab="${projectTab}"]`).focus({preventScroll:true});}
if(b.dataset.signal){signalFilter=b.dataset.signal;render();document.querySelector(`[data-signal="${signalFilter}"]`).focus({preventScroll:true});}
if(b.dataset.folder){libraryFilter=b.dataset.folder;render();document.querySelector(`[data-folder="${libraryFilter}"]`).focus({preventScroll:true});}
if(b.dataset.journalMode){journalMode=b.dataset.journalMode;render();document.querySelector(`[data-journal-mode="${journalMode}"]`).focus({preventScroll:true});}
if(b.dataset.book!==undefined)selectBook(Number(b.dataset.book));
if(b.id==='prev-book')selectBook(selectedBook-1);if(b.id==='next-book')selectBook(selectedBook+1);
if(b.dataset.openBook!==undefined)openBook(Number(b.dataset.openBook));
if(b.dataset.note){const n=notes.find(x=>x.id===Number(b.dataset.note));openBook(n.book,n.id);}
if(b.dataset.toc)showEntry(Number(b.dataset.toc),1);
if(b.id==='prev-entry')turn(-1);if(b.id==='next-entry')turn(1);
if(b.id==='new-note')editNote();if(b.id==='reader-edit')editNote(notes.find(n=>n.id===selectedNote));
if(b.dataset.dialog)dialog(b.dataset.dialog);if(b.dataset.close){if(b.dataset.close==='reader')closeReader();else $('#'+b.dataset.close).close();}
if(b.dataset.jumpNote){$('#drawer').close();if($('#reader').open)$('#reader').close();const n=notes.find(x=>x.id===Number(b.dataset.jumpNote));page('journal');openBook(n.book,n.id);}
if(b.dataset.searchProject){$('#drawer').close();currentProject=b.dataset.searchProject;projectTab='overview';page('projects');}
});
document.addEventListener('input',e=>{if(e.target.id==='file-search')$('#file-rows').innerHTML=fileRows(e.target.value);if(e.target.id==='journal-search')$('#journal-results').innerHTML=journalRows(e.target.value);if(e.target.id==='global-query')searchResults(e.target.value);});
document.addEventListener('change',e=>{if(e.target.id==='motion-toggle')document.body.classList.toggle('motion-off',!e.target.checked);if(e.target.id==='sticky-done'){notes.find(n=>n.id===2).done=e.target.checked;toast('已更新本次预览中的跟进状态');}});
$('#note-form').onsubmit=e=>{e.preventDefault();const title=$('#note-title').value.trim(),content=$('#note-content').value.trim();if(!title||!content)return;const existing=notes.find(n=>n.id===editing),book=Number($('#note-book').value);const n={...existing,id:editing||Math.max(...notes.map(n=>n.id))+1,book,date:'2026.09.06',type:$('#note-type').value,title,content,next:$('#note-next').value.trim()};if(existing&&existing.book!==book)delete n.source;if(editing)notes=notes.map(x=>x.id===editing?n:x);else notes.push(n);selectedBook=book;$('#editor').close();if($('#reader').open)showEntry(n.id);if(currentPage==='journal')render();toast('已保存到本次预览 · 刷新后恢复示例');};
$('#reader').addEventListener('close',()=>{if(currentPage==='journal'&&journalMode==='albums'){positionBooks();$('#journal-below').innerHTML=selectedMarkup();}});
document.addEventListener('keydown',e=>{const editable=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){if(!$('#editor').open&&!$('#reader').open){e.preventDefault();dialog('search');}return;}if(editable||$('#editor').open||$('#drawer').open)return;if($('#reader').open&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();turn(e.key==='ArrowLeft'?-1:1);}else if(currentPage==='journal'&&journalMode==='albums'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();selectBook(selectedBook+(e.key==='ArrowLeft'?-1:1));document.querySelector(`[data-book="${selectedBook}"]`).focus();}else if(e.target.matches('[role=tab]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=['overview','quote','measures','history'];projectTab=tabs[(tabs.indexOf(projectTab)+(e.key==='ArrowRight'?1:3))%4];render();document.querySelector(`[data-project-tab="${projectTab}"]`).focus();}});
window.addEventListener('resize',positionBooks);window.addEventListener('hashchange',()=>page(location.hash.slice(1)));
if(['dashboard','projects','intelligence','library','journal'].includes(location.hash.slice(1)))currentPage=location.hash.slice(1);
hydrate();render();
