const $=s=>document.querySelector(s);
document.querySelectorAll('.nav').forEach(b=>b.setAttribute('aria-label',b.dataset.page==='projects'?'项目档案':b.dataset.page==='journal'?'工作手记':'资料与证据'));
const money=n=>n.toFixed(2);
const domains=[['显示模组',420,400,'替代验证'],['驱动方案',95,110,'配套依赖'],['结构组件',48,48,'冻结明细'],['电源方案',27,27,'冻结明细'],['包装',12,12,'冻结明细'],['ODM 加工',8,8,'冻结明细']];
$('#cost-rows').innerHTML=domains.map(([name,current,target,evidence],i)=>`<tr><td><span class="domain-label"><i style="opacity:${1-i*.09}"></i>${name}</span></td><td class="num">${money(current)}</td><td class="num">${money(target)}</td><td class="num ${target<current?'saving':''}">${target===current?'—':(target>current?'+':'−')+money(Math.abs(target-current))}</td><td><button class="source-button" data-dialog="domain" data-domain="${i}">${evidence}</button></td></tr>`).join('');
let notes=[
{id:1,project:'M27-Q',date:'09.05',type:'决策记录',title:'把屏的节省，和驱动的增本一起看',intro:'单看显示模组可以省 20 元，但驱动补偿需要增加 15 元。整包才是可交付的方案。',judgment:'当前标准成本为 640.50 元。该变更包的 BOM 净节省为 5.00 元，按 5% 平台费率计入后，预计标准成本为 635.25 元。距离 630.00 元目标，仍有 5.25 元缺口。',next:'安排样机验证，确认驱动能力和显示效果。证据补齐前不标记实施。'},
{id:2,project:'M27-Q',date:'09.04',type:'报价复核',title:'包装口径未对齐，暂不比较第三家报价',intro:'第三家供应商的报价没有明确包装材料和附件范围。当前总价暂不进入可比低价。',judgment:'先锁定相同产品规格、数量、币种、税费和交付条件，再比较整机报价。保留原始批次，不用手动改价补齐差异。',next:'请供应商补充包装及附件清单，收到后更新可比状态。'},
{id:3,project:'G32-U',date:'09.03',type:'规格判断',title:'高刷新率需求，先回到真实使用场景',intro:'评审讨论集中在刷新率提升，但现有反馈不能直接证明用户愿意为此付出更多。',judgment:'将原声主题关联到显示效果与使用场景，区分明确需求和推断。在规格调整之前记录影响模块与验证方式。',next:'补充用户场景和竞品规格证据，形成下一轮评审材料。'},
{id:4,project:'M27-Q',date:'09.02',type:'阶段复盘',title:'这轮评审，把事实版本先固定下来',intro:'会前同时修改报价和规格，很容易让讨论中的数字来自不同时间点。',judgment:'本次资料固定 BOM、规格和费率来源。当前事实、目标和待实施机会分别展示，不在同一个总额里混算。',next:'下次会前先核对阶段成本包的来源清单。'},
{id:5,project:'G32-U',date:'09.01',type:'现场记录',title:'屏方案的两条路线，分别保留比较依据',intro:'方案 A 的成本更低，方案 B 的显示能力更强；两条路线解决的问题并不相同。',judgment:'暂不按最低报价选型。记录性能边界、报价来源和测试条件，下一轮再决定取舍。',next:'分别补齐两条路线的验证记录。'},
{id:6,project:'M27-Q',date:'08.28',type:'阶段记录',title:'CDCP 成本评审后，留下三个待确认项',intro:'评审结束并不代表所有成本项都已确认。未知项需要保留责任和补齐时间。',judgment:'把下一步动作写进记录，并关联到项目。后续变动回到当时的版本核查，避免用最新价格解释历史判断。',next:'跟进供应商补价和技术验证，形成 PDCP 输入。'}
];
let selected=1,folder='all',editing=false;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function page(name){$('.page:not([hidden])')?.setAttribute('hidden','');$('#'+name).hidden=false;document.querySelectorAll('.nav[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$('#breadcrumb').textContent=name==='journal'?'工作手记':'项目档案';if(name==='journal')renderNotes();window.scrollTo({top:0});}
function tab(name){document.querySelectorAll('.tab-panel').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('[role=tab]').forEach(e=>e.setAttribute('aria-selected',String(e.dataset.tab===name)));}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p)page(p.dataset.page);const t=e.target.closest('[data-tab]');if(t)tab(t.dataset.tab);const d=e.target.closest('[data-dialog]');if(d)openDialog(d.dataset.dialog,d.dataset.domain);});
document.querySelectorAll('[role=tab]').forEach((button,index,array)=>button.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const next=array[(index+(e.key==='ArrowRight'?1:-1)+array.length)%array.length];next.focus();tab(next.dataset.tab);}));
function renderNotes(){const q=$('#note-search').value.trim().toLowerCase();const rows=notes.filter(n=>(folder==='all'||n.project===folder)&&[n.title,n.intro,n.judgment].join(' ').toLowerCase().includes(q));$('#note-count').textContent=rows.length+' 条记录';if(!rows.some(n=>n.id===selected))selected=rows[0]?.id;$('#note-list').innerHTML=rows.length?rows.map(n=>`<button class="note-card ${selected===n.id?'active':''}" data-note="${n.id}" aria-pressed="${selected===n.id}"><small><span>${n.date} · ${n.type}</span><span>${n.project}</span></small><strong>${escapeHtml(n.title)}</strong><p>${escapeHtml(n.intro)}</p></button>`).join(''):'<p class="muted">没有匹配的手记，试试更短的关键词。</p>';$('#paper').hidden=!rows.length;if(rows.length)showNote(selected);}
function showNote(id){selected=id;const n=notes.find(n=>n.id===id);if(!n)return;document.querySelectorAll('.note-card').forEach(e=>{e.classList.toggle('active',Number(e.dataset.note)===id);e.setAttribute('aria-pressed',String(Number(e.dataset.note)===id));});document.querySelector('.paper-evidence').hidden=n.id!==1;$('#paper-project').textContent=n.project+' / 项目现场';$('#paper-date').textContent='2026.'+n.date;$('#paper-kind').textContent=n.type;$('#paper-title').textContent=n.title;$('#paper-body').innerHTML=`<p>${escapeHtml(n.intro)}</p><h3>我的判断</h3><p>${escapeHtml(n.judgment)}</p><div class="note-next">下一步<br>${escapeHtml(n.next)}</div>`;$('#paper').getAnimations().forEach(a=>a.cancel());$('#paper').animate([{opacity:.35,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:180,easing:'cubic-bezier(.22,1,.36,1)'});$('#pin-note').textContent=n.done?'已完成':'重点跟进';$('#pin-note').classList.toggle('done',!!n.done);}
$('#note-list').onclick=e=>{const b=e.target.closest('[data-note]');if(b)showNote(Number(b.dataset.note));};
document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{folder=b.dataset.folder;document.querySelectorAll('[data-folder]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});renderNotes();});
$('#note-search').oninput=renderNotes;$('#toggle-density').onclick=()=>{const compact=$('#note-list').classList.toggle('compact');$('#toggle-density').textContent=compact?'摘要列表':'紧凑列表';};$('#pin-note').onclick=()=>{const n=notes.find(n=>n.id===selected);n.done=!n.done;showNote(selected);};
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,2800);}
function editor(edit){editing=edit;const n=edit?notes.find(n=>n.id===selected):null;$('#editor-heading').textContent=edit?'编辑手记':'写一条手记';$('#edit-project').value=n?.project||'M27-Q';$('#edit-title').value=n?.title||'';$('#edit-body').value=n?[n.intro,n.judgment,n.next].join('\n\n'):'';$('#note-editor').showModal();$('#edit-title').focus();}
$('#new-note').onclick=()=>editor(false);$('#edit-note').onclick=()=>editor(true);$('#close-editor').onclick=()=>$('#note-editor').close();$('#note-form').onsubmit=e=>{e.preventDefault();const title=$('#edit-title').value.trim(),body=$('#edit-body').value.trim();if(!title||!body)return;const paragraphs=body.split(/\n\s*\n/);const n={id:editing?selected:Math.max(...notes.map(n=>n.id))+1,project:$('#edit-project').value,date:'09.05',type:'工作记录',title,intro:paragraphs[0],judgment:paragraphs[1]||'本条记录尚未补充独立判断。',next:paragraphs.slice(2).join('\n')||'待补充下一步动作。'};if(editing)notes=notes.map(x=>x.id===selected?n:x);else notes.unshift(n);selected=n.id;folder='all';$('#note-search').value='';document.querySelectorAll('[data-folder]').forEach(x=>{x.classList.toggle('selected',x.dataset.folder==='all');x.setAttribute('aria-pressed',String(x.dataset.folder==='all'));});document.querySelector('.nav[data-page=journal] small').textContent=String(notes.length).padStart(2,'0');document.querySelector('[data-folder=all] b').textContent=String(notes.length).padStart(2,'0');for(const code of ['M27-Q','G32-U'])document.querySelector('[data-folder="'+code+'"] b').textContent=String(notes.filter(n=>n.project===code).length).padStart(2,'0');renderNotes();$('#note-editor').close();toast('已保存在本次设计预览中');};
const line=(name,value)=>`<div class="evidence-line"><span>${name}</span><b>${value}</b></div>`;
function openDialog(kind,index){let title='',body='',eyebrow='M27-Q / 产品规格 v3';switch(kind){
case 'change':title='CP–014 · 整包复核';body='<span class="pill amber">技术可行 · 尚未实施</span><h3>依赖一起确认，金额一起守恒</h3><p>显示方案节省与驱动补偿属于同一变更包。必要项缺证据时，整包不进入已确认机会。</p>'+line('显示模组 · 420 → 400','−¥20.00')+line('驱动方案 · 95 → 110','+¥15.00')+line('BOM 净变化','−¥5.00')+line('标准成本净变化（含 5% 费率）','−¥5.25')+'<h3>还需要什么</h3><div class="evidence-card"><small>技术验证</small><strong>完成样机显示效果与驱动验证</strong><p>验证结果、来源版本、责任人需与方案对应。</p></div><p>确认机会不代表实施。实施后应关联新冻结 BOM 与生效证据。</p>';break;
case 'version':title='冻结事实 · BOM v3';body='<span class="pill green">只读快照</span>'+line('冻结时间','2026.09.05 14:32')+line('产品规格','v3 · QHD / 165 Hz')+line('可分解成本','¥610.00')+line('平台费率','5.00%')+line('标准成本','¥640.50')+'<h3>来源清单</h3><p>6 个成本领域、对应规格与费率共同冻结。历史快照不随今日器件价变化。</p>';break;
case 'domain':{const [name,current,target]=domains[Number(index)];title=name+' · 成本依据';body=line('当前冻结单价 / 台','¥'+money(current))+line('方案目标 / 台','¥'+money(target))+line('来源版本','BOM v3')+line('证据状态','已确认')+'<h3>查看方式</h3><p>正式接入时展示全部源行、数量、单价及原始报价定位。目标变化保留变更包关系，不覆盖当前事实。</p>';break;}
case 'quote':title='原始报价与可比条件';body=line('批次范围','当前第 3 轮')+line('币种 / 税费','CNY / 未税')+line('数量 / 交付','1 台 / EXW')+line('固定规格','产品规格 v3')+'<h3>待补证据</h3><p>ODM C 尚需确认包装和附件范围。完整报价单在正式产品中由证据定位打开，本预览不连接真实文件。</p>';break;
case 'export':title='阶段成本包 · 预览';body='<p>先复核以下来源，再生成阶段交付材料。</p>'+line('成本口径','冻结 BOM v3')+line('规格 / 费率','v3 / 5%')+line('标准成本','¥640.50')+line('财务目标','¥630.00')+line('未覆盖差额','¥10.50')+'<h3>交付内容</h3><p>项目定位、当前成本、目标缺口、变更包依赖、报价依据与后续动作。本设计稿仅展示交付预览，不生成正式报告。</p>';break;
case 'ai':title='围绕当前项目协作';eyebrow='AI 协作 / 本地';body='<p>当前上下文：M27-Q · 产品规格 v3 · BOM v3。建议先引用来源，再形成判断。</p><h3>可以从这里开始</h3><button class="search-result" data-dialog="change">解释 CP–014 的净成本影响<small>使用当前变更包与费率</small></button><button class="search-result" data-dialog="quote">检查三家报价是否可比<small>逐项核对报价条件</small></button><h3>结果边界</h3><p>AI 产出先作为草稿。确认、实施与冻结是不同动作。预览中不启动模型或云端请求。</p>';break;
case 'library':title='资料与证据';body='<div class="evidence-card"><small>项目档案 / M27-Q</small><strong>报价、规格与冻结记录</strong><p>从业务对象进入证据，保持同一条来源关系。</p></div><button class="search-result" data-dialog="version">BOM v3 · 冻结快照<small>2026.09.05</small></button><button class="search-result" data-dialog="quote">第 3 轮供应商报价<small>3 家供应商 · 1 项口径待补</small></button>';break;
case 'recent':title='最近动态';body=line('09.05 14:32','冻结 BOM v3')+line('09.05 11:10','复核 CP–014')+line('09.04 16:20','记录报价口径缺口')+'<p>时间与事件来自对应记录，空状态不显示“刚刚”。以上为演示时间。</p>';break;
case 'projects':title='项目档案';body=projectsMarkup();break;
case 'search':title='搜索工作空间';body='<label><input id="global-query" aria-label="搜索项目和手记" placeholder="项目代号、手记或证据" style="width:100%"></label><div class="search-results" id="search-results"></div>';break;
default:title='关于这份设计预览';body='<p>本稿展示项目控制台与工作手记的视觉、交互方向。所有数值和记录均为虚构，不读取 CostHub 数据库。</p><h3>操作体验</h3><p>切换项目工作区、打开证据侧栏、筛选文件夹、搜索手记、编辑和新增记录。支持键盘与减少动态效果设置。</p>';
}$('#dialog-title').textContent=title;$('#dialog-eyebrow').textContent=eyebrow;$('#dialog-body').innerHTML=body;if(!$('#inspector').open)$('#inspector').showModal();if(kind==='search'){const input=$('#global-query');input.oninput=()=>{const q=input.value.trim().toLowerCase();$('#search-results').innerHTML=notes.filter(n=>(n.project+' '+n.title).toLowerCase().includes(q)).map(n=>`<button class="search-result" data-search-note="${n.id}">${escapeHtml(n.title)}<small>${n.project} · 工作手记</small></button>`).join('')||'<p>没有匹配结果。</p>';};input.oninput();input.focus();}}
function projectsMarkup(){return '<button class="search-result" id="project-result">M27-Q · 27″ QHD<small>PDCP · 当前标准成本 ¥640.50</small></button><div class="evidence-card" style="margin-top:12px"><small>其他项目 · 仅展示目录</small><strong>G32-U / M24-F / D27-C</strong><p>本稿完整设计 M27-Q；其他项目详情在实施阶段复用同一结构。</p></div>';}
$('#dialog-body').onclick=e=>{const n=e.target.closest('[data-search-note]');if(n){$('#inspector').close();page('journal');folder='all';document.querySelectorAll('[data-folder]').forEach(x=>{x.classList.toggle('selected',x.dataset.folder==='all');x.setAttribute('aria-pressed',String(x.dataset.folder==='all'));});$('#note-search').value='';renderNotes();showNote(Number(n.dataset.searchNote));}if(e.target.closest('#project-result')){$('#inspector').close();page('projects');}};
$('#close-dialog').onclick=$('#done-dialog').onclick=()=>$('#inspector').close();document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('#note-editor').open)openDialog('search');}});
renderNotes();

