"""Seed comprehensive CostHub demo data into the release database.

The script is intentionally idempotent: it keeps user data and replaces only
rows related to DEMO projects/parts generated by this script.
"""

from __future__ import annotations

import shutil
import sqlite3
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "src-tauri" / "target" / "release" / "monitor_cost.db"
STAMP = datetime.now().strftime("%Y%m%d_%H%M%S")


SCHEMA = """
CREATE TABLE IF NOT EXISTS trend_items (id INTEGER PRIMARY KEY AUTOINCREMENT, query_category TEXT NOT NULL, category_type TEXT DEFAULT '直接查询', trend_direction TEXT DEFAULT '', confidence_level TEXT DEFAULT '', summary TEXT DEFAULT '', suggested_action TEXT DEFAULT '', raw_search_results TEXT DEFAULT '', last_updated_at TEXT DEFAULT '', magnitude_min REAL, magnitude_max REAL, magnitude_reference TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS trend_part_mapping (id INTEGER PRIMARY KEY AUTOINCREMENT, trend_item_id INTEGER NOT NULL, part_id INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS trend_sources (id INTEGER PRIMARY KEY AUTOINCREMENT, trend_item_id INTEGER NOT NULL, source_title TEXT DEFAULT '', source_url TEXT DEFAULT '', excerpt TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS trend_conversations (id INTEGER PRIMARY KEY AUTOINCREMENT, trend_item_id INTEGER NOT NULL, question TEXT DEFAULT '', answer TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS trend_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT, trend_item_id INTEGER NOT NULL, query_time TEXT DEFAULT (datetime('now','localtime')), source_type TEXT DEFAULT 'direct_query', direction TEXT DEFAULT '', confidence TEXT DEFAULT '', confidence_level TEXT DEFAULT '', summary TEXT DEFAULT '', suggested_action TEXT DEFAULT '', skill_used TEXT DEFAULT '', magnitude_min REAL, magnitude_max REAL, magnitude_reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS trend_insight_dimensions (id INTEGER PRIMARY KEY AUTOINCREMENT, trend_snapshot_id INTEGER NOT NULL, dimension_type TEXT DEFAULT '', dimension_order INTEGER DEFAULT 0, content TEXT DEFAULT '', evidence_strength TEXT DEFAULT '', data_points TEXT DEFAULT '', source_title TEXT DEFAULT '', source_url TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS trend_key_events (id INTEGER PRIMARY KEY AUTOINCREMENT, trend_snapshot_id INTEGER NOT NULL, event_date TEXT DEFAULT '', event_description TEXT DEFAULT '', impact_direction TEXT DEFAULT '', source_title TEXT DEFAULT '', source_url TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS material_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, category_name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS part_suppliers (id INTEGER PRIMARY KEY AUTOINCREMENT, part_id INTEGER NOT NULL, supplier_name TEXT NOT NULL, unit_price REAL DEFAULT 0, price REAL DEFAULT 0, moq INTEGER DEFAULT 0, lead_time TEXT DEFAULT '', priority INTEGER DEFAULT 0, share_ratio REAL DEFAULT 0, is_active INTEGER DEFAULT 1, remark TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS supplier_price_history (id INTEGER PRIMARY KEY AUTOINCREMENT, part_id INTEGER NOT NULL, supplier_name TEXT NOT NULL, old_price REAL DEFAULT 0, new_price REAL DEFAULT 0, change_reason TEXT DEFAULT '', changed_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS decomposition_tree (id INTEGER PRIMARY KEY AUTOINCREMENT, root_part_id INTEGER, parent_id INTEGER, component_name TEXT NOT NULL, cost_ratio_estimate REAL, source_type TEXT DEFAULT 'user_confirmed', node_type TEXT DEFAULT 'structural', insight_status TEXT DEFAULT 'pending', trend_item_id INTEGER, remark TEXT DEFAULT '', ai_insights TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')), updated_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS decomposition_history (id INTEGER PRIMARY KEY AUTOINCREMENT, root_part_id INTEGER NOT NULL, timestamp TEXT DEFAULT (datetime('now','localtime')), summary TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS rollup_contributions (id INTEGER PRIMARY KEY AUTOINCREMENT, parent_snapshot_id INTEGER NOT NULL, child_component_id INTEGER NOT NULL, cost_ratio_used REAL, direction_used TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS rollup_feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, component_id INTEGER NOT NULL, component_name TEXT DEFAULT '', ai_direction TEXT DEFAULT '', ai_summary TEXT DEFAULT '', ai_confidence_level TEXT DEFAULT '', user_corrected_direction TEXT DEFAULT '', user_corrected_confidence_level TEXT DEFAULT '', correction_reason TEXT DEFAULT '', user_corrected_summary TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS analysis_checklist (id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT DEFAULT '', check_order INTEGER DEFAULT 0, item_description TEXT NOT NULL, strength_level TEXT DEFAULT 'observing', trigger_count INTEGER DEFAULT 0, first_triggered_at TEXT DEFAULT '', last_triggered_at TEXT DEFAULT '', is_active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS checklist_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, checklist_id INTEGER NOT NULL, question_snippet TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS outbound_request_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp TEXT DEFAULT (datetime('now','localtime')), method TEXT DEFAULT '', url TEXT DEFAULT '', status_code INTEGER DEFAULT 0, response_time_ms INTEGER DEFAULT 0, error_message TEXT DEFAULT '');
"""


def add_column(conn: sqlite3.Connection, table: str, definition: str) -> None:
    name = definition.split()[0]
    columns = {row[1] for row in conn.execute(f"PRAGMA table_info({table})")}
    if name not in columns:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {definition}")


def insert(conn: sqlite3.Connection, sql: str, values: tuple) -> int:
    return int(conn.execute(sql, values).lastrowid)


def main() -> None:
    if not DB_PATH.exists():
        raise SystemExit(f"Database not found: {DB_PATH}")
    backup = DB_PATH.with_name(f"monitor_cost.backup_before_demo_{STAMP}.db")
    shutil.copy2(DB_PATH, backup)

    conn = sqlite3.connect(DB_PATH, timeout=30)
    conn.execute("PRAGMA foreign_keys=OFF")
    conn.executescript(SCHEMA)
    for table, definition in [
        ("parts", "trend_enabled INTEGER DEFAULT 0"),
        ("parts", "trend_query_category TEXT DEFAULT ''"),
        ("parts", "trend_category_type TEXT DEFAULT '直接查询'"),
        ("projects", "sort_order INTEGER DEFAULT 0"),
        ("competitors", "sort_order INTEGER DEFAULT 0"),
        ("project_boms", "cost REAL DEFAULT 0"),
        ("project_boms", "is_reference INTEGER DEFAULT 0"),
        ("project_boms", "reference_remark TEXT DEFAULT ''"),
        ("project_boms", "is_deleted INTEGER DEFAULT 0"),
    ]:
        add_column(conn, table, definition)

    # Remove only data created by an earlier run of this script.
    demo_projects = [r[0] for r in conn.execute("SELECT id FROM projects WHERE code LIKE 'DEMO-%'")]
    demo_parts = [r[0] for r in conn.execute("SELECT id FROM parts WHERE model LIKE 'DEMO-%'")]
    demo_competitors = [r[0] for r in conn.execute("SELECT id FROM competitors WHERE remark LIKE '%CostHub演示数据%'")]
    for pid in demo_projects:
        module_ids = [r[0] for r in conn.execute("SELECT id FROM modules WHERE project_id=?", (pid,))]
        for mid in module_ids:
            conn.execute("DELETE FROM module_items WHERE module_id=?", (mid,))
        for table in ("modules", "project_boms", "project_cost_reviews", "project_targets", "project_measures"):
            conn.execute(f"DELETE FROM {table} WHERE project_id=?", (pid,))
        conn.execute("DELETE FROM product_scores WHERE ref_type='project' AND ref_id=?", (pid,))
        conn.execute("DELETE FROM projects WHERE id=?", (pid,))
    for cid in demo_competitors:
        conn.execute("DELETE FROM competitor_boms WHERE competitor_id=?", (cid,))
        conn.execute("DELETE FROM product_scores WHERE ref_type='competitor' AND ref_id=?", (cid,))
        conn.execute("DELETE FROM competitors WHERE id=?", (cid,))
    for part_id in demo_parts:
        for table in ("part_price_history", "part_suppliers", "supplier_price_history", "trend_part_mapping"):
            conn.execute(f"DELETE FROM {table} WHERE part_id=?", (part_id,))
        conn.execute("DELETE FROM parts WHERE id=?", (part_id,))
    conn.execute("DELETE FROM competitor_parts WHERE model LIKE 'DEMO-%'")
    conn.execute("DELETE FROM product_features WHERE name LIKE 'DEMO-%'")
    conn.execute("DELETE FROM trend_items WHERE raw_search_results='CostHub演示数据'")
    conn.execute("DELETE FROM material_categories WHERE category_name LIKE 'DEMO-%'")
    conn.execute("DELETE FROM decomposition_tree WHERE remark LIKE '%CostHub演示数据%'")
    conn.execute("DELETE FROM decomposition_history WHERE summary LIKE '%CostHub演示数据%'")
    conn.execute("DELETE FROM analysis_checklist WHERE item_description LIKE 'DEMO-%'")
    conn.execute("DELETE FROM outbound_request_logs WHERE url LIKE 'https://demo.costhub.local/%'")
    conn.execute("DELETE FROM api_providers WHERE provider_name LIKE 'DEMO-%'")

    part_rows = [
        ("其他", "显示模组", "面板", "27寸 QHD IPS 165Hz 面板", "DEMO-PANEL-Q27", 420.0, "2560x1440, 165Hz, 400nit", "DEMO-P27Q165", "核心报价物料", 1, "面板", "直接查询"),
        ("硬件类", "主控IC", "Scaler IC", "高刷显示主控", "DEMO-RTD2799BF", 42.8, "QHD 180Hz, DP1.4", "DEMO-P27Q165", "主板核心器件", 1, "Scaler IC", "直接查询"),
        ("硬件类", "存储", "DDR", "DDR4 2Gb", "DEMO-DDR4-2G", 12.4, "x16, 1.2V", "DEMO-P27Q165", "两家供应商报价", 1, "DDR存储", "直接查询"),
        ("硬件类", "接口IC", "USB Hub", "USB-C Hub控制器", "DEMO-VL817", 18.6, "USB 3.1 Gen1", "DEMO-P32U60", "扩展接口", 0, "", "直接查询"),
        ("结构类", "塑胶件", "后壳", "27寸后壳注塑件", "DEMO-COVER-27", 38.5, "阻燃ABS, 喷涂", "DEMO-P27Q165", "含模具摊销", 1, "ABS塑料", "直接查询"),
        ("结构类", "金属件", "支架", "升降旋转支架", "DEMO-STAND-ERG", 88.0, "升降130mm, 旋转90度", "DEMO-P27Q165", "结构降本重点", 1, "铝材", "直接查询"),
        ("电源类", "电源板", "内置电源", "90W内置电源板", "DEMO-PSU-90W", 58.0, "AC 100-240V", "DEMO-P27Q165", "通过安规", 0, "", "直接查询"),
        ("线材类", "视频线", "DP线", "DP1.4线 1.8m", "DEMO-DP14-18", 9.5, "8K认证, 黑色", "DEMO-P27Q165", "附件报价", 0, "", "直接查询"),
        ("包材类", "彩箱", "外箱", "27寸彩盒彩箱", "DEMO-CARTON-27", 16.8, "五层瓦楞, 彩印", "DEMO-P27Q165", "含内衬", 1, "瓦楞纸", "直接查询"),
        ("加工费类", "PCBA加工", "SMT贴片", "主板SMT加工", "DEMO-SMT-MAIN", 13.0, "双面贴装, 含测试", "DEMO-P27Q165", "ODM加工报价", 0, "", "直接查询"),
        ("软件类", "固件", "Firmware", "OSD固件授权", "DEMO-FW-OSD", 5.0, "含一年维护", "DEMO-P27Q165", "一次性分摊", 0, "", "直接查询"),
        ("其他", "人工", "组装测试", "整机组装与老化测试", "DEMO-ASSY-QA", 24.0, "组装+4小时老化", "DEMO-P27Q165", "制造费用", 0, "", "直接查询"),
    ]
    parts: dict[str, int] = {}
    for row in part_rows:
        part_id = insert(conn, "INSERT INTO parts (main_category,sub_category,category,name,model,cost,specs,projects,remark,trend_enabled,trend_query_category,trend_category_type) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", row)
        parts[row[4]] = part_id
        conn.executemany("INSERT INTO part_price_history (part_id,old_cost,new_cost,changed_at) VALUES (?,?,?,?)", [
            (part_id, round(row[5] * 1.08, 2), round(row[5] * 1.03, 2), "2026-04-15 10:00:00"),
            (part_id, round(row[5] * 1.03, 2), row[5], "2026-07-20 10:00:00"),
        ])

    project_rows = [
        ("DEMO-P27Q165", "27寸QHD 165Hz电竞显示器", "在研", "中高端", "进行中", "27", "2560x1440", "165Hz", "Fast IPS", 3.0, 8.0, 10),
        ("DEMO-P24F180", "24寸FHD 180Hz电竞显示器", "在研", "主流级", "进行中", "24", "1920x1080", "180Hz", "IPS", 3.0, 7.0, 20),
        ("DEMO-P32U60", "32寸4K商务显示器", "已完成", "高端", "已完成", "32", "3840x2160", "60Hz", "IPS", 4.0, 10.0, 30),
    ]
    projects: dict[str, int] = {}
    for row in project_rows:
        projects[row[0]] = insert(conn, "INSERT INTO projects (code,name,project_type,tier,status,screen_size,resolution,refresh_rate,panel_type,platform_fee_rate,profit_rate,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", row)

    bom_plan = {
        "DEMO-P27Q165": [("DEMO-PANEL-Q27", "显示模组", 1), ("DEMO-RTD2799BF", "主板模块", 1), ("DEMO-DDR4-2G", "主板模块", 2), ("DEMO-COVER-27", "结构模块", 1), ("DEMO-STAND-ERG", "结构模块", 1), ("DEMO-PSU-90W", "电源模块", 1), ("DEMO-DP14-18", "附件包", 1), ("DEMO-CARTON-27", "包材", 1), ("DEMO-SMT-MAIN", "加工测试", 1), ("DEMO-FW-OSD", "软件", 1), ("DEMO-ASSY-QA", "加工测试", 1)],
        "DEMO-P24F180": [("DEMO-PANEL-Q27", "显示模组", 0.76), ("DEMO-RTD2799BF", "主板模块", 1), ("DEMO-DDR4-2G", "主板模块", 1), ("DEMO-COVER-27", "结构模块", 0.82), ("DEMO-PSU-90W", "电源模块", 0.8), ("DEMO-CARTON-27", "包材", 0.8), ("DEMO-SMT-MAIN", "加工测试", 1)],
        "DEMO-P32U60": [("DEMO-PANEL-Q27", "显示模组", 1.35), ("DEMO-VL817", "主板模块", 1), ("DEMO-DDR4-2G", "主板模块", 2), ("DEMO-STAND-ERG", "结构模块", 1.15), ("DEMO-PSU-90W", "电源模块", 1), ("DEMO-ASSY-QA", "加工测试", 1.2)],
    }
    for code, items in bom_plan.items():
        module_names = sorted({x[1] for x in items})
        module_ids = {name: insert(conn, "INSERT INTO modules (project_id,name,description) VALUES (?,?,?)", (projects[code], name, f"{code} {name}演示模块")) for name in module_names}
        for model, module_name, quantity in items:
            p = next(x for x in part_rows if x[4] == model)
            conn.execute("INSERT INTO project_boms (project_id,part_id,module_name,quantity,cost,remark) VALUES (?,?,?,?,?,?)", (projects[code], parts[model], module_name, quantity, p[5], "CostHub演示BOM"))
            conn.execute("INSERT INTO module_items (module_id,part_id,part_name,part_model,main_category,sub_category,cost,quantity,remark) VALUES (?,?,?,?,?,?,?,?,?)", (module_ids[module_name], parts[model], p[3], model, p[0], p[1], p[5], quantity, "可复用模块器件"))

    for code, cost in [("DEMO-P27Q165", 735.2), ("DEMO-P24F180", 512.6), ("DEMO-P32U60", 968.4)]:
        pid = projects[code]
        conn.executemany("INSERT INTO project_cost_reviews (project_id,stage,reviewed_cost,reviewer,reviewed_at,remark) VALUES (?,?,?,?,?,?)", [(pid, "初次报价", cost * 1.08, "成本工程师", "2026-05-10 14:00:00", "供应商首轮报价"), (pid, "议价后", cost, "项目经理", "2026-07-18 16:00:00", "第二轮定点报价")])
        conn.executemany("INSERT INTO project_targets (project_id,domain,target_cost,remark) VALUES (?,?,?,?)", [(pid, "硬件类", cost * 0.18, "核心器件目标"), (pid, "结构类", cost * 0.16, "结构件目标"), (pid, "整机", cost * 0.96, "量产目标成本")])
        conn.executemany("INSERT INTO project_measures (project_id,main_category,measure,status,due_date,owner,remark) VALUES (?,?,?,?,?,?,?)", [(pid, "硬件类", "主控与DDR组合议价", "进行中", "2026-08-15", "张工", "目标降低8元"), (pid, "结构类", "支架铝件改冲压钢件评估", "已完成", "2026-07-25", "李工", "已验证样件"), (pid, "包材类", "内衬材料减量", "待执行", "2026-09-01", "王工", "需通过跌落测试")])

    competitors: dict[str, int] = {}
    for row in [("AOC", "Q27G4", "中高端", 1599, 760, 5, "CostHub演示数据：竞品拆机估算", 10), ("Dell", "G2724D", "高端", 2099, 820, 6, "CostHub演示数据：渠道报价", 20)]:
        competitors[row[1]] = insert(conn, "INSERT INTO competitors (brand,model,tier,market_price,bom_cost,platform_fee_rate,remark,sort_order) VALUES (?,?,?,?,?,?,?,?)", row)
    for model, cid in competitors.items():
        factor = 1.0 if model == "Q27G4" else 1.08
        for part_model, module_name, qty in bom_plan["DEMO-P27Q165"][:8]:
            p = next(x for x in part_rows if x[4] == part_model)
            conn.execute("INSERT INTO competitor_boms (competitor_id,part_id,part_name,part_model,module_name,estimated_cost,quantity,is_mapped,our_part_name,our_part_model,our_cost,our_quantity) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", (cid, parts[part_model], p[3], f"{model}-{part_model}", module_name, round(p[5] * factor, 2), qty, 1, p[3], part_model, p[5], qty))
    conn.executemany("INSERT INTO competitor_parts (main_category,sub_category,category,name,model,cost,specs,remark) VALUES (?,?,?,?,?,?,?,?)", [("硬件类", "主控IC", "Scaler IC", "竞品高刷主控", "DEMO-COMP-SCALER", 46.2, "QHD 180Hz", "拆机估算"), ("结构类", "塑胶件", "后壳", "竞品27寸后壳", "DEMO-COMP-COVER", 41.0, "ABS喷涂", "供应商报价估算")])

    feature_ids = []
    for name, weight in [("DEMO-成本竞争力", 1.5), ("DEMO-显示规格", 1.2), ("DEMO-接口丰富度", 1.0), ("DEMO-结构体验", 0.8)]:
        feature_ids.append(insert(conn, "INSERT INTO product_features (name,weight) VALUES (?,?)", (name, weight)))
    for code, pid in projects.items():
        scores = [9, 8, 7, 8] if code == "DEMO-P27Q165" else ([8, 7, 6, 6] if code == "DEMO-P24F180" else [6, 9, 9, 9])
        conn.executemany("INSERT INTO product_scores (ref_type,ref_id,feature_id,score) VALUES ('project',?,?,?)", [(pid, fid, score) for fid, score in zip(feature_ids, scores)])
    for model, cid in competitors.items():
        scores = [7, 8, 7, 7] if model == "Q27G4" else [5, 8, 8, 9]
        conn.executemany("INSERT INTO product_scores (ref_type,ref_id,feature_id,score) VALUES ('competitor',?,?,?)", [(cid, fid, score) for fid, score in zip(feature_ids, scores)])

    supplier_models = ["DEMO-PANEL-Q27", "DEMO-RTD2799BF", "DEMO-DDR4-2G", "DEMO-COVER-27", "DEMO-STAND-ERG"]
    for model in supplier_models:
        base = next(x[5] for x in part_rows if x[4] == model)
        for idx, (name, ratio, factor) in enumerate([("京东方演示供应商", 60, 1.0), ("华星演示供应商", 40, 1.035)]):
            price = round(base * factor, 2)
            conn.execute("INSERT INTO part_suppliers (part_id,supplier_name,unit_price,price,moq,lead_time,priority,share_ratio,is_active,remark) VALUES (?,?,?,?,?,?,?,?,?,?)", (parts[model], name, price, price, 1000, "4-6周", idx + 1, ratio, 1, "CostHub演示报价"))
            conn.execute("INSERT INTO supplier_price_history (part_id,supplier_name,old_price,new_price,change_reason,changed_at) VALUES (?,?,?,?,?,?)", (parts[model], name, round(price * 1.05, 2), price, "季度议价", "2026-07-01 09:00:00"))

    trend_ids: dict[str, int] = {}
    trend_rows = [("面板", "下降", "高", "QHD电竞面板供应改善，短期报价温和下行", "分批锁价，保留季度调价条款", -5, -2), ("Scaler IC", "持平", "中", "高刷主控供需平衡，价格波动有限", "双供验证后再扩大议价", -1, 2), ("DDR存储", "下降", "高", "存储现货价回落并传导至模组报价", "延后大批量锁价", -8, -3), ("铝材", "上升", "中", "能源和运输成本对铝型材报价形成支撑", "评估钢件替代和轻量化", 2, 6), ("ABS塑料", "持平", "中", "原料供给稳定，注塑加工费变化不大", "维持月度询价", -2, 2), ("瓦楞纸", "上升", "低", "旺季包装需求可能推升纸价", "提前确认包材用量", 1, 4)]
    for category, direction, confidence, summary, action, low, high in trend_rows:
        tid = insert(conn, "INSERT INTO trend_items (query_category,category_type,trend_direction,confidence_level,summary,suggested_action,raw_search_results,last_updated_at,magnitude_min,magnitude_max,magnitude_reference) VALUES (?,?,?,?,?,?,?,?,?,?,?)", (category, "直接查询", direction, confidence, summary, action, "CostHub演示数据", "2026-07-28 10:30:00", low, high, "未来3个月价格变化%"))
        trend_ids[category] = tid
        conn.execute("INSERT INTO trend_sources (trend_item_id,source_title,source_url,excerpt) VALUES (?,?,?,?)", (tid, f"{category}行业周报（演示）", f"https://demo.costhub.local/source/{tid}", summary))
        conn.execute("INSERT INTO trend_conversations (trend_item_id,question,answer) VALUES (?,?,?)", (tid, f"{category}对当前项目有什么影响？", f"建议：{action}。该回答为测试数据。"))
        sid = insert(conn, "INSERT INTO trend_snapshots (trend_item_id,query_time,source_type,direction,confidence,confidence_level,summary,suggested_action,skill_used,magnitude_min,magnitude_max,magnitude_reference) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", (tid, "2026-07-28 10:30:00", "direct_query", direction, confidence, confidence, summary, action, "demo-market-analysis", low, high, "未来3个月价格变化%"))
        conn.executemany("INSERT INTO trend_insight_dimensions (trend_snapshot_id,dimension_type,dimension_order,content,evidence_strength,data_points,source_title,source_url) VALUES (?,?,?,?,?,?,?,?)", [(sid, "供给", 1, f"{category}供应端产能与交期变化", "强", "产能利用率、交期", "演示行业周报", f"https://demo.costhub.local/dimension/{tid}/1"), (sid, "需求", 2, "显示器终端需求保持平稳", "中", "出货量、渠道库存", "演示渠道跟踪", f"https://demo.costhub.local/dimension/{tid}/2")])
        conn.execute("INSERT INTO trend_key_events (trend_snapshot_id,event_date,event_description,impact_direction,source_title,source_url) VALUES (?,?,?,?,?,?)", (sid, "2026-07-15", f"{category}主要供应商更新季度报价", direction, "演示事件记录", f"https://demo.costhub.local/event/{tid}"))
    for model, pid in parts.items():
        category = next(x[10] for x in part_rows if x[4] == model)
        if category in trend_ids:
            conn.execute("INSERT INTO trend_part_mapping (trend_item_id,part_id) VALUES (?,?)", (trend_ids[category], pid))
    conn.executemany("INSERT OR IGNORE INTO material_categories (category_name) VALUES (?)", [(f"DEMO-{x}",) for x in ("面板", "芯片", "存储", "铝材", "塑料", "纸材")])

    root = insert(conn, "INSERT INTO decomposition_tree (root_part_id,parent_id,component_name,cost_ratio_estimate,source_type,node_type,insight_status,remark,ai_insights) VALUES (?,?,?,?,?,?,?,?,?)", (parts["DEMO-PANEL-Q27"], None, "27寸QHD电竞显示器整机", 100, "user_confirmed", "root", "completed", "CostHub演示数据", "整机成本拆解根节点"))
    children = []
    for name, ratio, trend_cat in [("显示模组", 45, "面板"), ("主板模块", 18, "Scaler IC"), ("电源模块", 10, None), ("结构件", 14, "铝材"), ("包材附件", 8, "瓦楞纸"), ("加工测试", 5, None)]:
        child = insert(conn, "INSERT INTO decomposition_tree (root_part_id,parent_id,component_name,cost_ratio_estimate,source_type,node_type,insight_status,trend_item_id,remark,ai_insights) VALUES (?,?,?,?,?,?,?,?,?,?)", (parts["DEMO-PANEL-Q27"], root, name, ratio, "user_confirmed", "structural", "completed" if trend_cat else "pending", trend_ids.get(trend_cat), "CostHub演示数据", f"{name}占整机成本约{ratio}%"))
        children.append((child, ratio, trend_cat))
    conn.execute("INSERT INTO decomposition_history (root_part_id,summary) VALUES (?,?)", (parts["DEMO-PANEL-Q27"], "CostHub演示数据：完成六大模块拆解"))
    panel_snapshot = conn.execute("SELECT id FROM trend_snapshots WHERE trend_item_id=? ORDER BY id DESC LIMIT 1", (trend_ids["面板"],)).fetchone()[0]
    for child, ratio, trend_cat in children:
        conn.execute("INSERT INTO rollup_contributions (parent_snapshot_id,child_component_id,cost_ratio_used,direction_used) VALUES (?,?,?,?)", (panel_snapshot, child, ratio, "下降" if trend_cat in ("面板", "Scaler IC") else "持平"))
    conn.execute("INSERT INTO rollup_feedback (component_id,component_name,ai_direction,ai_summary,ai_confidence_level,user_corrected_direction,user_corrected_confidence_level,correction_reason,user_corrected_summary) VALUES (?,?,?,?,?,?,?,?,?)", (children[0][0], "显示模组", "下降", "面板供给改善", "高", "下降", "高", "结合ODM最新报价确认", "预计未来一季度下降约3%"))

    checklist_ids = []
    for order, row in enumerate([("趋势分析", "DEMO-是否同时核对供给、需求和库存？", "validated", 6), ("供应商", "DEMO-是否比较至少两家供应商的同规格报价？", "observing", 3), ("成本拆解", "DEMO-各子项成本占比合计是否接近100%？", "validated", 8), ("项目评审", "DEMO-目标成本是否有对应降本措施？", "learning", 2)], 1):
        checklist_ids.append(insert(conn, "INSERT INTO analysis_checklist (category,check_order,item_description,strength_level,trigger_count,first_triggered_at,last_triggered_at,is_active) VALUES (?,?,?,?,?,?,?,1)", (row[0], order, row[1], row[2], row[3], "2026-06-01 09:00:00", "2026-07-28 11:00:00")))
    for cid in checklist_ids:
        conn.execute("INSERT INTO checklist_logs (checklist_id,question_snippet,created_at) VALUES (?,?,?)", (cid, "演示问题：请分析27寸QHD项目的成本趋势", "2026-07-28 11:00:00"))
    conn.executemany("INSERT INTO outbound_request_logs (timestamp,method,url,status_code,response_time_ms,error_message) VALUES (?,?,?,?,?,?)", [("2026-07-28 10:29:58", "GET", "https://demo.costhub.local/search?q=panel", 200, 438, ""), ("2026-07-28 10:30:02", "POST", "https://demo.costhub.local/llm/analyze", 200, 1260, ""), ("2026-07-28 10:31:00", "GET", "https://demo.costhub.local/search?q=ddr", 429, 302, "演示：请求频率限制")])
    conn.executemany("INSERT INTO api_providers (provider_type,provider_name,api_key,base_url,model_name,is_active,priority,is_preset,monthly_quota_note,registration_url) VALUES (?,?,?,?,?,?,?,?,?,?)", [("search", "DEMO-Serper搜索", "demo-placeholder-key", "https://google.serper.dev", "", 0, 1, 1, "演示配置，不可真实调用", "https://serper.dev"), ("llm", "DEMO-DeepSeek分析", "demo-placeholder-key", "https://api.deepseek.com", "deepseek-chat", 0, 1, 1, "演示配置，不可真实调用", "https://platform.deepseek.com")])

    conn.commit()
    counts = {}
    for table in ["parts", "projects", "modules", "project_boms", "competitors", "competitor_boms", "part_suppliers", "trend_items", "trend_snapshots", "decomposition_tree", "analysis_checklist", "product_scores"]:
        counts[table] = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    integrity = conn.execute("PRAGMA integrity_check").fetchone()[0]
    conn.close()
    print(f"database={DB_PATH}")
    print(f"backup={backup}")
    print("counts=" + ", ".join(f"{k}:{v}" for k, v in counts.items()))
    print(f"integrity={integrity}")


if __name__ == "__main__":
    main()
